default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: <%= ENV["BACKEND_DATABASE_NAME"] %>
  username: <%= ENV["BACKEND_DATABASE_USERNAME"] %>
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
